### ISSUE TITLE
House is still a tube.

### ISSUE THREAD

**Issue by oObqpdOo** [thasti/LittleComputerPeople#39]
HouseView stellt das Haus immer noch als Reihe dar.

**Comment by thasti** [comment]
To fix this bug:
* XML must include the attached rooms
* XML-Parser must parse the attached rooms and set them to the Rooms
* Subject needs to have a possibility to change rooms in the staircase (up/down)
* HouseView needs to view the House-Graphic instead of the adjacent bitmaps and be vertically scrollable instead of horizontally

**Comment by thasti** [comment]
Fixed, @oObqpdOo
